OPENIMAGES_CLASS_FOLDERS = {
    "Fire hydrant": "fire_hydrant",
    "Bicycle": "bicycle",
    "Car": "car",
    "Traffic light": "traffic_light",
    "Tree": "tree",
    "House": "house",
    "Flag": "flag",
    "Street light": "street_light",
    "Flower": "flower",
    "Dog": "dog",
    "Cat": "cat",
    "Bird": "bird",
    "Horse": "horse",
    "Cow": "cow",
    "Sheep": "sheep",
    "Elephant": "elephant",
    "Zebra": "zebra",
    "Giraffe": "giraffe",
    "Boat": "boat",
    "Bus": "bus",
    "Truck": "truck",
    "Motorcycle": "motorcycle",
    "Airplane": "airplane",
    "Train": "train",
    "Chair": "chair",
    "Table": "table",
    "Bottle": "bottle",
    "Cup": "cup",
    "Book": "book",
    "Laptop": "laptop",
    "Mobile phone": "mobile_phone",
    "Backpack": "backpack",
    "Umbrella": "umbrella",
    "Clock": "clock",
    "Camera": "camera",
    "Shoe": "shoe",
    "Hat": "hat",
    "Apple": "apple",
    "Banana": "banana",
    "Orange": "orange",
    "Pizza": "pizza",
    "Cake": "cake",
}

BROAD_OPENIMAGES_CLASSES = [
    "Tortoise",
    "Sea turtle",
    "Football",
    "Ambulance",
    "Ladder",
    "Toothbrush",
    "Syringe",
    "Sink",
    "Toy",
    "Snowman",
    "Beer",
    "Chopsticks",
    "Bird",
    "Traffic light",
    "Croissant",
    "Cucumber",
    "Radish",
    "Towel",
    "Doll",
    "Glove",
    "Belt",
    "Sunglasses",
    "Ball",
    "Backpack",
    "Bicycle",
    "Boat",
    "Surfboard",
    "Boot",
    "Headphones",
    "Hot dog",
    "Shorts",
    "Bus",
    "Screwdriver",
    "Laptop",
    "Dress",
    "Bear",
    "Waffle",
    "Pancake",
    "Pretzel",
    "Bagel",
    "Tower",
    "Teapot",
    "Person",
    "Bee",
    "Balloon",
    "Wrench",
    "Tent",
    "Lantern",
    "Toaster",
    "Flashlight",
    "Necklace",
    "Scissors",
    "Computer keyboard",
    "Printer",
    "Traffic sign",
    "Chair",
    "Shirt",
    "Cheese",
    "Sock",
    "Fire hydrant",
    "Suitcase",
    "Muffin",
    "Clock",
    "Cattle",
    "Cello",
    "Camel",
    "Coat",
    "Giraffe",
    "Guitar",
    "Helicopter",
    "Jeans",
    "Kettle",
    "Knife",
    "Mobile phone",
    "Motorcycle",
    "Mouse",
    "Mug",
    "Orange",
    "Oven",
    "Owl",
    "Plant",
    "Refrigerator",
    "Remote control",
    "Sandwich",
    "Table",
    "Tablet computer",
    "Television",
    "Tennis racket",
    "Tire",
    "Toilet",
    "Tomato",
    "Train",
    "Truck",
    "Umbrella",
    "Washing machine",
    "Wine glass",
    "Zebra",
    "Airplane",
    "Apple",
    "Banana",
    "Book",
    "Bottle",
    "Car",
    "Cat",
    "Cake",
    "Camera",
    "Dog",
    "Elephant",
    "Flag",
    "Flower",
    "Horse",
    "House",
    "Pizza",
    "Sheep",
    "Tree",
    "Box",
    "Candle",
    "Coffee cup",
    "Cookie",
    "Door",
    "Envelope",
    "Fork",
    "Fountain",
    "Fox",
    "French fries",
    "Frog",
    "Hamburger",
    "Handbag",
    "Hat",
    "Lion",
    "Lizard",
    "Microphone",
    "Microwave oven",
    "Monkey",
    "Mushroom",
    "Piano",
    "Pillow",
    "Pumpkin",
    "Rabbit",
    "Raven",
    "Rose",
    "Scarf",
    "Sea lion",
    "Skirt",
    "Snake",
    "Spider",
    "Spoon",
    "Strawberry",
    "Swan",
    "Tap",
    "Taxi",
    "Tiger",
    "Violin",
    "Window",
    "Woman",
]


CLASS_MAP = {
    "fire_hydrant": "消防栓",
    "bicycle": "自行车",
    "car": "汽车",
    "traffic_light": "信号灯",
    "tree": "树",
    "house": "房子",
    "flag": "旗帜",
    "street_light": "路灯",
    "star": "星星",
    "flower": "花",
    "dog": "狗",
    "cat": "猫",
    "bird": "鸟",
    "horse": "马",
    "cow": "牛",
    "sheep": "羊",
    "elephant": "大象",
    "zebra": "斑马",
    "giraffe": "长颈鹿",
    "boat": "船",
    "bus": "公交车",
    "truck": "卡车",
    "motorcycle": "摩托车",
    "airplane": "飞机",
    "train": "火车",
    "chair": "椅子",
    "table": "桌子",
    "bottle": "瓶子",
    "cup": "杯子",
    "book": "书",
    "laptop": "笔记本电脑",
    "mobile_phone": "手机",
    "backpack": "背包",
    "umbrella": "雨伞",
    "clock": "时钟",
    "camera": "相机",
    "shoe": "鞋",
    "hat": "帽子",
    "apple": "苹果",
    "banana": "香蕉",
    "orange": "橙子",
    "pizza": "披萨",
    "cake": "蛋糕",
    "tortoise": "陆龟",
    "sea_turtle": "海龟",
    "football": "足球",
    "ambulance": "救护车",
    "ladder": "梯子",
    "toothbrush": "牙刷",
    "syringe": "注射器",
    "sink": "水槽",
    "toy": "玩具",
    "snowman": "雪人",
    "beer": "啤酒",
    "chopsticks": "筷子",
    "croissant": "羊角面包",
    "cucumber": "黄瓜",
    "radish": "萝卜",
    "towel": "毛巾",
    "doll": "玩偶",
    "glove": "手套",
    "belt": "腰带",
    "sunglasses": "太阳镜",
    "ball": "球",
    "surfboard": "冲浪板",
    "boot": "靴子",
    "headphones": "耳机",
    "hot_dog": "热狗",
    "shorts": "短裤",
    "screwdriver": "螺丝刀",
    "dress": "裙子",
    "bear": "熊",
    "waffle": "华夫饼",
    "pancake": "薄煎饼",
    "pretzel": "椒盐卷饼",
    "bagel": "贝果",
    "tower": "塔",
    "teapot": "茶壶",
    "person": "人",
    "bee": "蜜蜂",
    "balloon": "气球",
    "wrench": "扳手",
    "tent": "帐篷",
    "lantern": "灯笼",
    "toaster": "烤面包机",
    "flashlight": "手电筒",
    "necklace": "项链",
    "scissors": "剪刀",
    "computer_keyboard": "键盘",
    "printer": "打印机",
    "traffic_sign": "交通标志",
    "shirt": "衬衫",
    "cheese": "奶酪",
    "sock": "袜子",
    "suitcase": "行李箱",
    "muffin": "松饼",
    "cattle": "牛",
    "cello": "大提琴",
    "camel": "骆驼",
    "coat": "外套",
    "guitar": "吉他",
    "helicopter": "直升机",
    "jeans": "牛仔裤",
    "kettle": "水壶",
    "knife": "刀",
    "mouse": "鼠标",
    "mug": "马克杯",
    "oven": "烤箱",
    "owl": "猫头鹰",
    "plant": "植物",
    "refrigerator": "冰箱",
    "remote_control": "遥控器",
    "sandwich": "三明治",
    "tablet_computer": "平板电脑",
    "television": "电视",
    "tennis_racket": "网球拍",
    "tire": "轮胎",
    "toilet": "马桶",
    "tomato": "番茄",
    "washing_machine": "洗衣机",
    "wine_glass": "酒杯",
    "box": "盒子",
    "candle": "蜡烛",
    "coffee_cup": "咖啡杯",
    "cookie": "饼干",
    "door": "门",
    "envelope": "信封",
    "fork": "叉子",
    "fountain": "喷泉",
    "fox": "狐狸",
    "french_fries": "薯条",
    "frog": "青蛙",
    "hamburger": "汉堡",
    "handbag": "手提包",
    "lion": "狮子",
    "lizard": "蜥蜴",
    "microphone": "麦克风",
    "microwave_oven": "微波炉",
    "monkey": "猴子",
    "mushroom": "蘑菇",
    "piano": "钢琴",
    "pillow": "枕头",
    "pumpkin": "南瓜",
    "rabbit": "兔子",
    "raven": "乌鸦",
    "rose": "玫瑰",
    "scarf": "围巾",
    "sea_lion": "海狮",
    "skirt": "半身裙",
    "snake": "蛇",
    "spider": "蜘蛛",
    "spoon": "勺子",
    "strawberry": "草莓",
    "swan": "天鹅",
    "tap": "水龙头",
    "taxi": "出租车",
    "tiger": "老虎",
    "violin": "小提琴",
    "window": "窗户",
    "woman": "女人",
}


DEFAULT_OPENIMAGES_CLASSES = [
    "Fire hydrant",
    "Bicycle",
    "Car",
    "Traffic light",
    "Tree",
    "House",
    "Flag",
    "Street light",
    "Flower",
]


EXTENDED_OPENIMAGES_CLASSES = list(OPENIMAGES_CLASS_FOLDERS)


def slugify_label(label: str) -> str:
    cleaned = []
    for char in label.lower():
        if char.isalnum():
            cleaned.append(char)
        elif cleaned and cleaned[-1] != "_":
            cleaned.append("_")
    return "".join(cleaned).strip("_")


def folder_for_openimages_class(label: str) -> str:
    return OPENIMAGES_CLASS_FOLDERS.get(label, slugify_label(label))


def object_name_for_folder(folder: str, english_label: str | None = None) -> str:
    return CLASS_MAP.get(folder, english_label or folder.replace("_", " "))
